- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/brave.yml
    - include: tasks/dotfiles.yml
    - include: tasks/personal-projects.yml
